### ISSUE TITLE
请问编译出来的WiFi驱动   在Ubuntu上正常  centos7.4和openeuler22.03上不能用，请教大佬  不太懂这些。下面是openeuler22.03加载bcmdhd.ko时的日志

### ISSUE THREAD

**Issue by pathpass2** [CmST0us/tspi-linux-sdk-archived#14]
[  357.905503] [dhd] dhd_pri_open : no mutex held
[  357.905594] [dhd] dhd_pri_open : set mutex lock
[  357.905609] [dhd] [wlan0] dhd_open : Enter
[  357.905619] [dhd] Dongle Host Driver, version 101.10.361.20 (wlan=r892223-20220701-3)
[  357.905619] drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd compiled on Aug 18 2024 at 11:13:38
[  357.905619]
[  357.905651] [dhd] dhd_open: ######### called for ifidx=0 #########
[  357.905680] [dhd] [wlan0] wl_android_wifi_on : in g_wifi_on=0
[  357.905691] [dhd] wifi_platform_set_power = 1, delay: 200 msec
[  357.905700] [dhd] ======== PULL WL_REG_ON(-1) HIGH! ========
[  357.905710] [WLAN_RFKILL]: rockchip_wifi_power: 1
[  357.905721] [WLAN_RFKILL]: rockchip_wifi_power: toggle = false
[  357.905729] [WLAN_RFKILL]: wifi turn on power [GPIO-1-0]
[  358.212482] [dhd] sdio_sw_reset: Enter
[  358.212832] mmc_host mmc2: Bus speed (slot 0) = 375000Hz (slot req 400000Hz, actual 375000HZ div = 0)
[  358.259851] mmc2: queuing unknown CIS tuple 0x80 (2 bytes)
[  358.261907] mmc2: queuing unknown CIS tuple 0x80 (3 bytes)
[  358.263799] mmc2: queuing unknown CIS tuple 0x80 (3 bytes)
[  358.267893] mmc2: queuing unknown CIS tuple 0x80 (7 bytes)
[  358.273010] mmc2: queuing unknown CIS tuple 0x81 (9 bytes)
[  358.343468] mmc_host mmc2: Bus speed (slot 0) = 148500000Hz (slot req 150000000Hz, actual 148500000HZ div = 0)
[  358.353135] dwmmc_rockchip fe2c0000.dwmmc: Successfully tuned phase to 360
[  358.353342] [dhd] sdioh_start: set sd_f2_blocksize 256
[  358.353707] [dhd] dhd_bus_devreset: == Power ON ==
[  358.353975] [dhd] F1 signature read @0x18000000=0x15264345
[  358.358683] [dhd] F1 signature OK, socitype:0x1 chip:0x4345 rev:0x6 pkg:0x2
[  358.359696] [dhd] DHD: dongle ram size is set to 819200(orig 819200) at 0x198000
[  358.359842] [dhd] dhd_bus_devreset: making DHD_BUS_DOWN
[  358.359935] [dhd] dhdsdio_probe_init: making DHD_BUS_DOWN
[  358.360372] [dhd] dhd_conf_set_path_params : Final fw_path=/vendor/etc/firmware/fw_bcm43455c0_ag.bin
[  358.360425] [dhd] dhd_conf_set_path_params : Final nv_path=/vendor/etc/firmware/nvram_ap6255.txt
[  358.360449] [dhd] dhd_conf_set_path_params : Final clm_path=/vendor/etc/firmware/clm_bcm43455c0_ag.blob
[  358.360470] [dhd] dhd_conf_set_path_params : Final conf_path=/vendor/etc/firmware/config.txt
SIOCSIFFLAGS: Operation not permitted
[  358.360566] [dhd] dhd_os_open_image1: /vendor/etc/firmware/config.txt (240 bytes) open success
[  358.360848] [dhd] dhd_conf_read_pm_params : PM = 0
[  358.360891] [dhd] dhd_conf_read_pm_params : pm_in_suspend = 2
[  358.360944] [dhd] dhd_conf_read_others : keep_alive_period = 120000
[  358.360978] [dhd] dhd_conf_read_others : garp = 1
[root@openEuler ~]# [  358.361010] [dhd] dhd_conf_read_pm_params : suspend_bcn_li_dtim = 10
[  358.361053] [dhd] dhd_conf_read_others : wl_preinit = pm2_sleep_ret=20
[  358.361091] [dhd] dhd_conf_read_pkt_filter : pkt_filter_del id = 100 102 103 104 105 107
[  358.361179] [dhd] dhd_conf_read_pkt_filter : pkt_filter_add[0][] = 142 0 0 77 0xffffffffffffffffffffffffffffff 0x2F6465766963652F77616B6575702F
[  358.361970] [dhd] dhd_os_open_image1: /vendor/etc/firmware/fw_bcm43455c0_ag.bin (131 bytes) open success
[  358.362418] [dhd] dhdsdio_download_code_file: dhd_os_get_image_block failed (-5)
[  358.362456] [dhd] _dhdsdio_download_firmware: dongle image file download failed
[  358.362529] [dhd] dhd_bus_devreset Failed to download binary to the dongle
[  358.362571] [dhd] dhd_net_bus_devreset: dhd_bus_devreset: -35
[  358.362602] [dhd] ANDROID-ERROR) failed to power up wifi chip, retry again (0 left) **
[  358.362602]
[  358.362642] [dhd] dhd_rtt_deinit: ENTER
[  358.362664] [dhd] dhd_rtt_deinit: EXIT, err = 0
[  358.362691] [dhd] dhd_net_bus_devreset: dhd_bus_devreset: -35
[  358.362716] [dhd] wifi_platform_set_power = 0, delay: 0 msec
[  358.362738] [dhd] ======== PULL WL_REG_ON(-1) LOW! ========
[  358.362759] [WLAN_RFKILL]: rockchip_wifi_power: 0
[  358.362783] [WLAN_RFKILL]: rockchip_wifi_power: toggle = false
[  358.362803] [WLAN_RFKILL]: rockchip_wifi_power: toggle = false
[  358.362822] [WLAN_RFKILL]: wifi shut off power [GPIO-1-1]
[  358.362841] [dhd] ANDROID-ERROR) failed to power up wifi chip, max retry reached **
[  358.362841]
[  358.362864] [dhd] [wlan0] wl_android_wifi_on : Failed -35
[  358.362901] [dhd] dhd_open : wl_android_wifi_on failed (-35)
[  358.362923] [dhd] [wlan0] dhd_stop : Enter
[  358.362953] [dhd] [wlan0] wl_android_wifi_off : in g_wifi_on=0, on_failure=1
[  358.362971] [dhd] dhd_rtt_deinit: ENTER
[  358.362988] [dhd] dhd_rtt_deinit: EXIT, err = 0
[  358.363007] [dhd] dhd_net_bus_devreset: dhd_bus_devreset: -35
[  358.363101] [dhd] wifi_platform_set_power = 0, delay: 0 msec
[  358.363129] [dhd] ======== PULL WL_REG_ON(-1) LOW! ========
[  358.363166] [WLAN_RFKILL]: rockchip_wifi_power: 0
[  358.363186] [WLAN_RFKILL]: rockchip_wifi_power: toggle = false
[  358.363204] [WLAN_RFKILL]: rockchip_wifi_power: toggle = false
[  358.363222] [WLAN_RFKILL]: wifi shut off power [GPIO-1-1]
[  358.363242] [dhd] [wlan0] wl_android_wifi_off : out
[  358.363290] [dhd] dhd_os_wake_lock_destroy: wake lock count=1
[  358.363495] [dhd] [wlan0] dhd_stop : Exit
[  358.363529] [dhd] [wlan0] dhd_open : Exit ret=-1
[  358.363552] [dhd] Failed to open primary dev ret -1
[  358.363569] [dhd] dhd_pri_open : mutex is released.

**Comment by pathpass2** [comment]
ok  刚看到以前的issues   我跟之前的哥们一样  库不完整，已解决。非常感谢大佬。还有个问题，不知道为什么  不管是Ubuntu还是openeuler都会优先使用ipv6的网络，但是ipv6有时候又有问题，我只能禁用ipv6

**Comment by CmST0us** [comment]
这是ChatGPT4 的回答, 可以参考一下
在 Linux 系统中，如果你希望在同时启用了 IPv4 和 IPv6 的情况下优先使用 IPv4，你可以通过以下几种方法来实现：

### 1. 修改 `gai.conf` 配置文件
`gai.conf` 文件是用于配置 getaddrinfo() 函数的行为，这个函数用于将主机名解析为 IP 地址。

- 编辑 `/etc/gai.conf` 文件：
  ```bash
  sudo nano /etc/gai.conf
  ```

- 找到并取消注释以下行（去掉前面的 `#`）：
  ```bash
  precedence ::ffff:0:0/96  100
  ```

  这条规则指定了优先选择 IPv4 的地址族（`::ffff:0:0/96` 是 IPv4 映射到 IPv6 的地址范围）。

- 保存并退出编辑器。

### 2. 禁用 IPv6

如果不需要使用 IPv6，或者只想在特定接口或应用程序中禁用 IPv6，可以通过以下方法实现：

- **临时禁用 IPv6（针对当前会话）**：
  ```bash
  sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
  ```

- **永久禁用 IPv6**：
  编辑 `/etc/sysctl.conf` 文件：
  ```bash
  sudo nano /etc/sysctl.conf
  ```
  添加以下行：
  ```bash
  net.ipv6.conf.all.disable_ipv6 = 1
  net.ipv6.conf.default.disable_ipv6 = 1
  ```
  保存并退出编辑器，然后应用设置：
  ```bash
  sudo sysctl -p
  ```

### 3. 在应用程序级别配置
有些应用程序允许你通过配置文件或者命令行参数来指定优先使用 IPv4。例如，在 `curl` 中可以通过添加 `-4` 选项来强制使用 IPv4：

```bash
curl -4 http://example.com
```

使用这些方法，你可以在 Linux 系统中优先使用 IPv4 地址。

**Comment by pathpass2** [comment]
> 这是ChatGPT4的答案，可以参考一下 在Linux系统中，如果你希望在同时启用了IPv4和IPv6的情况下优先使用IPv4，你可以通过以下几种方法来实现：
> 
> ### 1. 修改`gai.conf`配置文件
> `gai.conf`文件是用于配置 getaddrinfo() 函数的行为，该函数用于将主机名解析为 IP 地址。
> 
> * 编辑`/etc/gai.conf`文件：
>   ```shell
>   sudo nano /etc/gai.conf
>   ```
> * 找到并取消注释以下行（去掉前面的`#`）：
>   ```shell
>   precedence ::ffff:0:0/96  100
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   这条规则指定了优先选择 IPv4 的所属地址（`::ffff:0:0/96`是 IPv4 映射到 IPv6 的地址范围）。
> * 保存并退出编辑器。
> 
> ### 2. 禁用IPv6
> 如果不需要使用 IPv6，或者在特定接口或应用程序中禁用 IPv6，可以通过以下方法实现：
> 
> * **临时取消IPv6（针对当前会话）**：
>   ```shell
>   sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
>   sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
>   ```
> * **永久取消IPv6**：
>   编辑`/etc/sysctl.conf`文件：
>   ```shell
>   sudo nano /etc/sysctl.conf
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   您以下行为：
>   ```shell
>   net.ipv6.conf.all.disable_ipv6 = 1
>   net.ipv6.conf.default.disable_ipv6 = 1
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   保存并退出编辑器，然后应用设置：
>   ```shell
>   sudo sysctl -p
>   ```
> 
> ### 3.在应用程序级别配置
> 有些应用程序允许您通过配置文件或者命令行参数来指定优先使用 IPv4。例如，在中`curl`可以通过添加`-4`选项来强制使用 IPv4：
> 
> ```shell
> curl -4 http://example.com
> ```
> 
> 使用这些方法，你可以在Linux系统中优先使用IPv4地址。

好的  非常感谢  我去试试
