### ISSUE TITLE
请教个rootfs的问题

### ISSUE THREAD

**Issue by pathpass2** [CmST0us/tspi-linux-sdk-archived#15]
用自己移植的：树莓派-openeuler-rootfs，rootfs第一次刷进去可以用，重启的话就不行了。提示rootfs的PARTUUID不对。我看sdk自带的Ubuntu-rootfs的uuid就是固定的

openeuler-rootfs第一次刷进去后显示的partuuid
<img width="632" alt="微信图片_20240821153559" src="https://github.com/user-attachments/assets/9d048d4d-8b6d-487c-93a6-e5ba3343a239">

重启后显示等待rootfs分区，此处uuid和openeuler的partuuid对不上
<img width="488" alt="ttl" src="https://github.com/user-attachments/assets/ec322f6b-c9b7-4187-8182-af332b8d1739">

请教大佬，这个rootfs的partuuid怎么改。

**Comment by CmST0us** [comment]
在 parameter.txt 文件里面

**Comment by CmST0us** [comment]
https://github.com/CmST0us/tspi-linux-sdk/blob/5873561da77de7028eafe010363fc3abc1cd223c/device/rockchip/.chips/rk3566_rk3568/parameter-buildroot-fit.txt#L12

**Comment by pathpass2** [comment]
大佬  不知道为啥  我重新编译   内核正常编译  但是编译完没有bcmdhd.ko    defconfig文件已经改了CONFIG_BCMDHD=y      CONFIG_WIFI_LOAD_DRIVER_WHEN_KERNEL_BOOTUP选项也已经取消，但是编译完还是没有bcmdhd.ko    我前面都是手动编译的ko文件。但是这几次再编译ko文件，提示我没有bcmdhd.ko的规则。Ubuntu18.04和Ubuntu22.04都是报这个错。

搞不懂了 我也不知道前面几次ko文件怎么编译出来的。

编译命令是：make ARCH=arm64  CROSS_COMPILE=aarch64-linux-gnu- ./drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/bcmdhd.ko

前面几次在Ubuntu18.04上面能成功，后面就不行了。sdk自带的交叉编译工具我也试了，也不行。

![1724331247185](https://github.com/user-attachments/assets/1ed46e56-3e2b-4292-98c3-b711d4a6943c)

**Comment by pathpass2** [comment]
> https://github.com/CmST0us/tspi-linux-sdk/blob/5873561da77de7028eafe010363fc3abc1cd223c/device/rockchip/.chips/rk3566_rk3568/parameter-buildroot-fit.txt#L12

这里我改了后，刷到parameter分区后依然是上面的报错。好像每次启动我这个rootfs的partuuid都会变。
![image](https://github.com/user-attachments/assets/738e42d5-df33-4b37-b2e0-0b7f73aae7d8)
这里我无论是改为rootfs的uuid还是改rootfs的partuuid。刷完都不行。

UUID="3a641c76-74db-48b5-8d31-d896bf2e0121" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="c9a76eda-6801-b64b-a19e-d5a37624b85c"

![image](https://github.com/user-attachments/assets/17398a73-92f1-42d1-820d-e1db49be6c95)


我没有用您的脚本打包，因为sdk里面没有openeuler，我直接制作了openeuler的rootfs镜像，然后刷到了rootfs分区。
![image](https://github.com/user-attachments/assets/152162b3-9012-4e72-9373-8b5ccc3c3d39)
刷完后自动重启能正常使用，但是一旦重启就会找不到rootfs

**Comment by pathpass2** [comment]
这个rootfs的partuuid就是在随机变。
第一次刷openeuler-rootfs，刷完正常使用。重启就找不到rootfs
UUID="3a641c76-74db-48b5-8d31-d896bf2e0121" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="c9a76eda-6801-b64b-a19e-d5a37624b85c"

然后再刷ubuntu的update，刷完后rootfs分区再刷openeuler的rootfs
/dev/mmcblk0p5: UUID="3a641c76-74db-48b5-8d31-d896bf2e0121" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="1c318175-98da-0644-a6a6-9af7b9b846d3"

这里partuuid就变了。

**Comment by pathpass2** [comment]
rootfs的问题找到了  openeuler的rootfs问题  换了个centos的rootfs就正常了  非常感谢大佬指点  驱动问题  我就先用以前编译出的驱动吧

**Comment by CmST0us** [comment]
> 大佬 不知道为啥 我重新编译 内核正常编译 但是编译完没有bcmdhd.ko defconfig文件已经改了CONFIG_BCMDHD=y CONFIG_WIFI_LOAD_DRIVER_WHEN_KERNEL_BOOTUP选项也已经取消，但是编译完还是没有bcmdhd.ko 我前面都是手动编译的ko文件。但是这几次再编译ko文件，提示我没有bcmdhd.ko的规则。Ubuntu18.04和Ubuntu22.04都是报这个错。
> 
> 搞不懂了 我也不知道前面几次ko文件怎么编译出来的。
> 
> 编译命令是：make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- ./drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/bcmdhd.ko
> 
> 前面几次在Ubuntu18.04上面能成功，后面就不行了。sdk自带的交叉编译工具我也试了，也不行。
> 
> ![1724331247185](https://private-user-images.githubusercontent.com/51352691/360437159-1ed46e56-3e2b-4292-98c3-b711d4a6943c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjYzNTUsIm5iZiI6MTcyNDQyNjA1NSwicGF0aCI6Ii81MTM1MjY5MS8zNjA0MzcxNTktMWVkNDZlNTYtM2UyYi00MjkyLTk4YzMtYjcxMWQ0YTY5NDNjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE1MTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MmY5MmY2NmQ0NTVlNDI1NDAxZTljNzFlYjRkMTE1MzE5YmY0ODMyNDE3YTkxNzcxYmM5YWYyZTg3Y2Q0ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mukcpUvbJGCKukWLm1sjsPgUo6NjWpCKHLKRxGjcnFs)

可以检查以下 CONFIG_AP6XXX 的设置， bcmdhd.ko 是依赖这个设置的

https://github.com/CmST0us/tspi-linux-sdk/blob/5873561da77de7028eafe010363fc3abc1cd223c/kernel/drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd/Makefile#L372

**Comment by CmST0us** [comment]
> > https://github.com/CmST0us/tspi-linux-sdk/blob/5873561da77de7028eafe010363fc3abc1cd223c/device/rockchip/.chips/rk3566_rk3568/parameter-buildroot-fit.txt#L12
> 
> 这里我改了后，刷到parameter分区后依然是上面的报错。好像每次启动我这个rootfs的partuuid都会变。 ![image](https://private-user-images.githubusercontent.com/51352691/360440551-738e42d5-df33-4b37-b2e0-0b7f73aae7d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjYzNTUsIm5iZiI6MTcyNDQyNjA1NSwicGF0aCI6Ii81MTM1MjY5MS8zNjA0NDA1NTEtNzM4ZTQyZDUtZGYzMy00YjM3LWIyZTAtMGI3ZjczYWFlN2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE1MTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzOGNlNjAzODVmODA2OTI2ZWM5ZTdlZmMxZTllMGUwMzNmODM1NzZkODE2OWEzOTdjNjI2MGU1ZWJjY2ViODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6keNpHUwyr0r3t470U37ZiWxIvzy8eKnaw9AV3yGiPU) 这里我无论是改为rootfs的uuid还是改rootfs的partuuid。刷完都不行。
> 
> UUID="3a641c76-74db-48b5-8d31-d896bf2e0121" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="c9a76eda-6801-b64b-a19e-d5a37624b85c"
> 
> ![image](https://private-user-images.githubusercontent.com/51352691/360440832-17398a73-92f1-42d1-820d-e1db49be6c95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjYzNTUsIm5iZiI6MTcyNDQyNjA1NSwicGF0aCI6Ii81MTM1MjY5MS8zNjA0NDA4MzItMTczOThhNzMtOTJmMS00MmQxLTgyMGQtZTFkYjQ5YmU2Yzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE1MTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjOWYzMzVlYTNiZDllNDRlZWU4M2VhYzgzOTk2YzVhODJjNDY3OTNmYzU3YTQ4N2E5NGMxMTA0YzgzY2I4MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vu_P7fxCkJhwomXGls8aTLKs5oMbv6X74gvzryJMK_Y)
> 
> 我没有用您的脚本打包，因为sdk里面没有openeuler，我直接制作了openeuler的rootfs镜像，然后刷到了rootfs分区。 ![image](https://private-user-images.githubusercontent.com/51352691/360441494-152162b3-9012-4e72-9373-8b5ccc3c3d39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjYzNTUsIm5iZiI6MTcyNDQyNjA1NSwicGF0aCI6Ii81MTM1MjY5MS8zNjA0NDE0OTQtMTUyMTYyYjMtOTAxMi00ZTcyLTkzNzMtOGI1Y2NjM2MzZDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE1MTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMjlhMTI5YTlhMTZmYTVjMzY0MDk4ZjU1YjNjNDEwM2I5NjIwZGE2NjU5ZDlhODE2MTVmMTYzMmMyNDMxZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V_cAiuPfjzDoBjlIsuk_YxZX-Jl1NXbkfIPr1y4TRhk) 刷完后自动重启能正常使用，但是一旦重启就会找不到rootfs

如果rootfs会变的画，可以在dts bootarg 里用root=/dev/mmcblk0p5设置 启动分区
https://github.com/CmST0us/tspi-linux-sdk/blob/5873561da77de7028eafe010363fc3abc1cd223c/kernel/arch/arm64/boot/dts/rockchip/tspi-rk3566-core-v10.dtsi#L31

**Comment by pathpass2** [comment]
> > > https://github.com/CmST0us/tspi-linux-sdk/blob/5873561da77de7028eafe010363fc3abc1cd223c/device/rockchip/.chips/rk3566_rk3568/parameter-buildroot-fit.txt#L12
> > 
> > 
> > 这里我改了后，刷到parameter分区后依然是上面的报错。好像每次启动我这个rootfs的partuuid都会变。 ![image](https://private-user-images.githubusercontent.com/51352691/360440551-738e42d5-df33-4b37-b2e0-0b7f73aae7d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjYzNTUsIm5iZiI6MTcyNDQyNjA1NSwicGF0aCI6Ii81MTM1MjY5MS8zNjA0NDA1NTEtNzM4ZTQyZDUtZGYzMy00YjM3LWIyZTAtMGI3ZjczYWFlN2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE1MTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzOGNlNjAzODVmODA2OTI2ZWM5ZTdlZmMxZTllMGUwMzNmODM1NzZkODE2OWEzOTdjNjI2MGU1ZWJjY2ViODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6keNpHUwyr0r3t470U37ZiWxIvzy8eKnaw9AV3yGiPU) 这里我无论是改为rootfs的uuid还是改rootfs的partuuid。刷完都不行。
> > UUID="3a641c76-74db-48b5-8d31-d896bf2e0121" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="c9a76eda-6801-b64b-a19e-d5a37624b85c"
> > ![image](https://private-user-images.githubusercontent.com/51352691/360440832-17398a73-92f1-42d1-820d-e1db49be6c95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjYzNTUsIm5iZiI6MTcyNDQyNjA1NSwicGF0aCI6Ii81MTM1MjY5MS8zNjA0NDA4MzItMTczOThhNzMtOTJmMS00MmQxLTgyMGQtZTFkYjQ5YmU2Yzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE1MTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjOWYzMzVlYTNiZDllNDRlZWU4M2VhYzgzOTk2YzVhODJjNDY3OTNmYzU3YTQ4N2E5NGMxMTA0YzgzY2I4MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vu_P7fxCkJhwomXGls8aTLKs5oMbv6X74gvzryJMK_Y)
> > 我没有用您的脚本打包，因为sdk里面没有openeuler，我直接制作了openeuler的rootfs镜像，然后刷到了rootfs分区。 ![image](https://private-user-images.githubusercontent.com/51352691/360441494-152162b3-9012-4e72-9373-8b5ccc3c3d39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjYzNTUsIm5iZiI6MTcyNDQyNjA1NSwicGF0aCI6Ii81MTM1MjY5MS8zNjA0NDE0OTQtMTUyMTYyYjMtOTAxMi00ZTcyLTkzNzMtOGI1Y2NjM2MzZDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE1MTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMjlhMTI5YTlhMTZmYTVjMzY0MDk4ZjU1YjNjNDEwM2I5NjIwZGE2NjU5ZDlhODE2MTVmMTYzMmMyNDMxZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V_cAiuPfjzDoBjlIsuk_YxZX-Jl1NXbkfIPr1y4TRhk) 刷完后自动重启能正常使用，但是一旦重启就会找不到rootfs
> 
> 如果rootfs会变的画，可以在dts bootarg 里用root=/dev/mmcblk0p5设置 启动分区
> 
> https://github.com/CmST0us/tspi-linux-sdk/blob/5873561da77de7028eafe010363fc3abc1cd223c/kernel/arch/arm64/boot/dts/rockchip/tspi-rk3566-core-v10.dtsi#L31

非常感谢

**Comment by pathpass2** [comment]
> /dev/mmcblk0p5

非常感谢  按照这个方法重新编译后rootfs能正常找到了
