### ISSUE TITLE
可以在编译前添加驱动吗？

### ISSUE THREAD

**Issue by huhaifan** [CmST0us/tspi-linux-sdk-archived#17]
ubuntu24.04编译的，可以正常编译和烧录。试图在泰山派上编译[驱动](https://github.com/WCHSoftGroup/ch9344ser_linux)，提示找不到内核的build文件夹。对linux编译不熟，是不是可以考虑在工程中直接集成这个驱动再编译？

**Comment by huhaifan** [comment]
解决啦，感谢 @CmST0us 制作的SDK。添加ch9344驱动步骤：

1. 将ch9344.c和ch9344.h拷到kernel/drivers/usb/serial文件夹
1. kernel/drivers/usb/serial/Kconfig中增加
	```
	config USB_SERIAL_CH9344
		tristate "USB Winchiphead CH9344 Single Port Serial Driver"
		help
		Say Y here if you want to use a Winchiphead CH9344 single port
		USB to serial adapter.

		To compile this driver as a module, choose M here: the
		module will be called ch.
	```
1. kernel/drivers/usb/serial/Markfile中增加
	`obj-$(CONFIG_USB_SERIAL_CH9344)			+= ch9344.o`
1. kernel/arch/arm64/configs/rockchip_linux_defconfig中增加
	`CONFIG_USB_SERIAL_CH9344=y`

**Comment by CmST0us** [comment]
赞！
