### ISSUE TITLE
VirtualBox虚拟机Ubuntu22.04 x86_64编译报错

### ISSUE THREAD

**Issue by JusticeShi** [CmST0us/tspi-linux-sdk-archived#18]
- 虚拟机：VirtualBox-7.0.20

- 镜像：ubuntu-22.04.4-desktop-amd64.iso

- 操作系统：Linux Ubuntu22 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

- gcc版本：11 和9 都试过报错

- 报错详细日志：

```
==========================================
          Start building kernel
==========================================
+ make -C kernel/ -j9 CROSS_COMPILE=/mnt/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu- ARCH=arm64 rockchip_linux_defconfig rockchip_linux_docker.config
make: Entering directory '/mnt/tspi-linux-sdk/kernel'
/mnt/tspi-linux-sdk/kernel/scripts/gcc-wrapper.py /mnt/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-gcc: unknown assembler invoked
scripts/Kconfig.include:47: Sorry, this assembler is not supported.
make[2]: *** [scripts/kconfig/Makefile:88: rockchip_linux_defconfig] Error 1
make[1]: *** [Makefile:639: rockchip_linux_defconfig] Error 2
make: *** [Makefile:357: __build_one_by_one] Error 2
make: Leaving directory '/mnt/tspi-linux-sdk/kernel'
ERROR: Running /mnt/tspi-linux-sdk/device/rockchip/common/scripts/mk-kernel.sh - run_command failed!
ERROR: exit code 2 from line 36:
    $@
ERROR: call stack:
    build-helper: run_command(36)
    mk-kernel.sh: do_build(46)
    mk-kernel.sh: build_hook(130)
    mk-kernel.sh: main(202)
ERROR: Running /mnt/tspi-linux-sdk/device/rockchip/common/build-hooks/99-all.sh - build_all failed!
ERROR: exit code 2 from line 26:
    "$SCRIPTS_DIR/mk-kernel.sh"
ERROR: call stack:
    99-all.sh: build_all(26)
    99-all.sh: build_allsave(107)
    99-all.sh: build_hook(132)
    build-helper: try_func(63)
    build-helper: try_hook(95)
    build-helper: source(158)
    99-all.sh: main(142)
ERROR: Running /mnt/tspi-linux-sdk/device/rockchip/common/build-hooks/99-all.sh - try_func build_hook allsave failed!
ERROR: exit code 2 from line 67:
    build_hook
ERROR: call stack:
    build-helper: try_func(67)
    build-helper: try_hook(95)
    build-helper: source(158)
    99-all.sh: main(142)
ERROR: Running ./build.sh - run_hooks build allsave failed!
ERROR: exit code 2 from line 152:
    /mnt/tspi-linux-sdk/device/rockchip/common/build-hooks/99-all.sh build allsave
ERROR: call stack:
    build.sh: run_hooks(152)
    build.sh: run_build_hooks(171)
    build.sh: main(437)
    build.sh: main(452)
ERROR: Running ./build.sh - run_build_hooks build allsave failed!
ERROR: exit code 2 from line 174:
    build
ERROR: call stack:
    build.sh: run_build_hooks(174)
    build.sh: main(437)
    build.sh: main(452)
```
请问大佬是哪里的问题导致的？

**Comment by JusticeShi** [comment]
> * 虚拟机：VirtualBox-7.0.20
> * 镜像：ubuntu-22.04.4-desktop-amd64.iso
> * 操作系统：Linux Ubuntu22 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
> * gcc版本：11 和9 都试过报错
> * 报错详细日志：
> 
> ```
> ==========================================
>           Start building kernel
> ==========================================
> + make -C kernel/ -j9 CROSS_COMPILE=/mnt/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu- ARCH=arm64 rockchip_linux_defconfig rockchip_linux_docker.config
> make: Entering directory '/mnt/tspi-linux-sdk/kernel'
> /mnt/tspi-linux-sdk/kernel/scripts/gcc-wrapper.py /mnt/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-gcc: unknown assembler invoked
> scripts/Kconfig.include:47: Sorry, this assembler is not supported.
> make[2]: *** [scripts/kconfig/Makefile:88: rockchip_linux_defconfig] Error 1
> make[1]: *** [Makefile:639: rockchip_linux_defconfig] Error 2
> make: *** [Makefile:357: __build_one_by_one] Error 2
> make: Leaving directory '/mnt/tspi-linux-sdk/kernel'
> ERROR: Running /mnt/tspi-linux-sdk/device/rockchip/common/scripts/mk-kernel.sh - run_command failed!
> ERROR: exit code 2 from line 36:
>     $@
> ERROR: call stack:
>     build-helper: run_command(36)
>     mk-kernel.sh: do_build(46)
>     mk-kernel.sh: build_hook(130)
>     mk-kernel.sh: main(202)
> ERROR: Running /mnt/tspi-linux-sdk/device/rockchip/common/build-hooks/99-all.sh - build_all failed!
> ERROR: exit code 2 from line 26:
>     "$SCRIPTS_DIR/mk-kernel.sh"
> ERROR: call stack:
>     99-all.sh: build_all(26)
>     99-all.sh: build_allsave(107)
>     99-all.sh: build_hook(132)
>     build-helper: try_func(63)
>     build-helper: try_hook(95)
>     build-helper: source(158)
>     99-all.sh: main(142)
> ERROR: Running /mnt/tspi-linux-sdk/device/rockchip/common/build-hooks/99-all.sh - try_func build_hook allsave failed!
> ERROR: exit code 2 from line 67:
>     build_hook
> ERROR: call stack:
>     build-helper: try_func(67)
>     build-helper: try_hook(95)
>     build-helper: source(158)
>     99-all.sh: main(142)
> ERROR: Running ./build.sh - run_hooks build allsave failed!
> ERROR: exit code 2 from line 152:
>     /mnt/tspi-linux-sdk/device/rockchip/common/build-hooks/99-all.sh build allsave
> ERROR: call stack:
>     build.sh: run_hooks(152)
>     build.sh: run_build_hooks(171)
>     build.sh: main(437)
>     build.sh: main(452)
> ERROR: Running ./build.sh - run_build_hooks build allsave failed!
> ERROR: exit code 2 from line 174:
>     build
> ERROR: call stack:
>     build.sh: run_build_hooks(174)
>     build.sh: main(437)
>     build.sh: main(452)
> ```
> 
> 请问大佬是哪里的问题导致的？

 找到原因了，系统没有定义python命令，指定到python2就可以了，以为编译用到了python2

**Comment by CmST0us** [comment]
赞！
