### ISSUE TITLE
请问有没有编译好的ubuntu或debian镜像呢？

### ISSUE THREAD

**Issue by mydear421** [CmST0us/tspi-linux-sdk-archived#19]
就是可以直接下载的到泰山派的ubuntu或者debian镜像呢，就是希望镜像大而全，含docker，各种常用工具链；就像香橙派适配的系统那种，方便做应用开发。

**Comment by mydear421** [comment]
希望能加上 嘉 泰山派底部4G_HUB2.0_ET100_HS扩展板 的支持

**Comment by CmST0us** [comment]
链接：https://pan.baidu.com/s/1yd-n9Xr-0quVid7sIeTM7Q?pwd=2653 
提取码：2653

**Comment by CmST0us** [comment]
这个固件可以满足你的需求

**Comment by mydear421** [comment]
太感谢了！我也测试了https://github.com/CmST0us/tspi-linux-sdk/releases/tag/gpu_mpp_driver里面网盘链接的系统，可以安装并运行docker
![微信图片_20240923132232](https://github.com/user-attachments/assets/eb24f26d-efb1-47ee-83b2-d8b905cf9e27)
