### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by LFZ1994** [CmST0us/tspi-linux-sdk-archived#4]
![tspi_2204](https://github.com/CmST0us/tspi-linux-sdk/assets/11564707/d7cd31a0-f14a-46e6-bd29-4a6d54408e95)

打扰了，使用立创的Docker编译环境编译这个版本SDK有报错，
请问有推荐的编译环境配置吗？

**Comment by CmST0us** [comment]
有没有安装 git-lfs
安装了git-lfs 之后
git lfs pull 更新一下

**Comment by CmST0us** [comment]
建议用 ubuntu-22.04
我是在真机 ubuntu-22.04上跑的
