### ISSUE TITLE
编译失败，日志如下，大佬请帮忙看看

### ISSUE THREAD

**Issue by kelvinchen1119** [CmST0us/tspi-linux-sdk-archived#5]
rez-ti@rezti-VirtualBox:~/tspi/tspi-linux-sdk$ ./build.sh 
Log saved at /home/rez-ti/tspi/tspi-linux-sdk/output/log/2024-04-14_22-36-29

Prebuilt toolchain (for kernel & loader):
/home/rez-ti/tspi/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-

==========================================
          Final configs
==========================================
RK_BOOT_FIT_ITS=boot.its
RK_BOOT_IMG=boot.img
RK_BUILDROOT_CFG=rockchip_rk3566
RK_CHIP=rk3566
RK_CHIP_FAMILY=rk3566
RK_DEBIAN_ARCH=arm64
RK_DEBIAN_ARM64=y
RK_DEBIAN_VERSION=bullseye
RK_DEFCONFIG=/home/rez-ti/tspi/tspi-linux-sdk/device/rockchip/.chips/rk3566_rk3568/tspi-rk3566-ubuntu_defconfig
RK_EXTRA_PARTITION_NUM=2
RK_EXTRA_PARTITION_STR=oem:oem:/oem:ext4:defaults:normal:auto:@userdata:userdata:/userdata:ext4:defaults:normal:auto:@@@
RK_KERNEL_ARCH=arm64
RK_KERNEL_ARM64=y
RK_KERNEL_CFG=rockchip_linux_defconfig
RK_KERNEL_DISTROBOOT_CMD=earlycon=uart8250,mmio32,0xfe660000 console=ttyFIQ0 root=PARTUUID=614e0000-0000 rw rootwait
RK_KERNEL_DTB=kernel/arch/arm64/boot/dts/rockchip/tspi-rk3566-user-v10-linux.dtb
RK_KERNEL_DTS=kernel/arch/arm64/boot/dts/rockchip/tspi-rk3566-user-v10-linux.dts
RK_KERNEL_IMG=kernel/arch/arm64/boot/Image
RK_KERNEL_VERSION=5.10
RK_KERNEL_VERSION_REAL=5.10
RK_MISC_IMG=blank-misc.img
RK_PARAMETER=parameter-buildroot-fit.txt
RK_PCBA_CFG=rockchip_rk3566_pcba
RK_RECOVERY_CFG=rockchip_rk3566_recovery
RK_RECOVERY_FIT_ITS=boot4recovery.its
RK_ROOTFS_SYSTEM=ubuntu
RK_ROOTFS_SYSTEM_UBUNTU=y
RK_ROOTFS_TYPE=ext4
RK_ROOTFS_UDEV_RULES=y
RK_SAVE_TRACKED=y
RK_SESSION=2024-04-14_22-36-29
RK_TOOLCHAIN=/home/rez-ti/tspi/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-
RK_UBOOT_CFG=rk3566
RK_USB_ADBD=y
RK_USB_ADBD_BASH=y
RK_USB_ADBD_TCP_PORT=5555
RK_USE_FIT_IMG=y
RK_WIFIBT_CHIP=ALL_AP
RK_WIFIBT_TTY=ttyS1
RK_YOCTO_CFG=rockchip-rk3568-evb
RK_YOCTO_DISPLAY_PLATFORM=wayland
RK_YOCTO_DISPLAY_PLATFORM_WAYLAND=y

==========================================
          Start building allsave
==========================================
==========================================
          Start building all images
==========================================
==========================================
          Start building uboot
==========================================
+ cd u-boot
+ ./make.sh CROSS_COMPILE=/home/rez-ti/tspi/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu- rk3566
## make  rk3568_defconfig rk3566.config -j16
#
# configuration written to .config
#
Using .config as base
Merging ./arch/../configs/rk3566.config
Value of CONFIG_BASE_DEFCONFIG is redefined by fragment ./arch/../configs/rk3566.config:
Previous value: CONFIG_BASE_DEFCONFIG=""
New value: CONFIG_BASE_DEFCONFIG="rk3568_defconfig"

Value of CONFIG_LOADER_INI is redefined by fragment ./arch/../configs/rk3566.config:
Previous value: CONFIG_LOADER_INI=""
New value: CONFIG_LOADER_INI="RK3566MINIALL.ini"

#
# merged configuration written to .config (needs make)
#
scripts/kconfig/conf  --oldconfig Kconfig
#
# configuration written to .config
#
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config.h
  CFG     u-boot.cfg
  GEN     include/autoconf.mk.dep
  CFG     spl/u-boot.cfg
  CFG     tpl/u-boot.cfg
  GEN     tpl/include/autoconf.mk
  GEN     include/autoconf.mk
  GEN     spl/include/autoconf.mk
  CHK     include/config/uboot.release
  CHK     include/generated/timestamp_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  CHK     include/generated/version_autogenerated.h
  CHK     include/generated/generic-asm-offsets.h
  CHK     include/generated/asm-offsets.h
  CHK     include/config.h
  CFG     u-boot.cfg
  HOSTCC  tools/mkenvimage.o
  HOSTCC  tools/image-host.o
  HOSTCC  tools/fit_image.o
  HOSTCC  tools/dumpimage.o
  HOSTCC  tools/mkimage.o
  HOSTCC  tools/rockchip/boot_merger.o
  HOSTCC  tools/rockchip/loaderimage.o
  HOSTLD  tools/mkenvimage
  HOSTLD  tools/loaderimage
  HOSTLD  tools/dumpimage
  HOSTLD  tools/mkimage
  HOSTLD  tools/boot_merger
  CC      arch/arm/cpu/armv8/fwcall.o
  LD      arch/arm/cpu/armv8/built-in.o
  CC      cmd/version.o
  CC      common/main.o
  LD      cmd/built-in.o
  LD      common/built-in.o
  CC      drivers/usb/gadget/f_fastboot.o
  CC      lib/display_options.o
  LD      lib/built-in.o
  LD      drivers/usb/gadget/built-in.o
  LD      u-boot
  OBJCOPY u-boot.srec
  OBJCOPY u-boot-nodtb.bin
start=$(/home/rez-ti/tspi/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-nm u-boot | grep __rel_dyn_start | cut -f 1 -d ' '); end=$(/home/rez-ti/tspi/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-nm u-boot | grep __rel_dyn_end | cut -f 1 -d ' '); tools/relocate-rela u-boot-nodtb.bin 0x00a00000 $start $end
  SYM     u-boot.sym
make[2]: 'arch/arm/dts/rk3568-evb.dtb' is up to date.
  COPY    u-boot.dtb
  CAT     u-boot-dtb.bin
  MKIMAGE u-boot.img
  MKIMAGE u-boot-dtb.img
  COPY    u-boot.bin
  ALIGN   u-boot.bin
  COPY    spl/u-boot-spl.dtb
  CC      spl/common/spl/spl.o
  CC      tpl/arch/arm/mach-rockchip/tpl.o
  CC      spl/arch/arm/cpu/armv8/fwcall.o
  CC      tpl/arch/arm/cpu/armv8/fwcall.o
  LD      tpl/arch/arm/mach-rockchip/built-in.o
  LD      spl/arch/arm/cpu/armv8/built-in.o
  LD      spl/common/spl/built-in.o
  LD      tpl/arch/arm/cpu/armv8/built-in.o
  CC      spl/lib/display_options.o
  LD      spl/lib/built-in.o
  LD      tpl/u-boot-tpl
  OBJCOPY tpl/u-boot-tpl-nodtb.bin
  COPY    tpl/u-boot-tpl.bin
  LD      spl/u-boot-spl
  OBJCOPY spl/u-boot-spl-nodtb.bin
  CAT     spl/u-boot-spl-dtb.bin
  COPY    spl/u-boot-spl.bin
  CFGCHK  u-boot.cfg
SEC=1
pack u-boot.itb okay! Input: /home/rez-ti/tspi/tspi-linux-sdk/rkbin/RKTRUST/RK3568TRUST.ini

FIT description: FIT Image with ATF/OP-TEE/U-Boot/MCU
Created:         Sun Apr 14 22:36:44 2024
 Image 0 (uboot)
  Description:  U-Boot
  Created:      Sun Apr 14 22:36:44 2024
  Type:         Standalone Program
  Compression:  uncompressed
  Data Size:    1305016 Bytes = 1274.43 KiB = 1.24 MiB
  Architecture: AArch64
  Load Address: 0x00a00000
  Entry Point:  unavailable
  Hash algo:    sha256
  Hash value:   57231f4495e645e616b06fe3e9bc0b1c29f593a0de69d36cbb05f238cbbd629c
 Image 1 (atf-1)
  Description:  ARM Trusted Firmware
  Created:      Sun Apr 14 22:36:44 2024
  Type:         Firmware
  Compression:  uncompressed
  Data Size:    167936 Bytes = 164.00 KiB = 0.16 MiB
  Architecture: AArch64
  Load Address: 0x00040000
  Hash algo:    sha256
  Hash value:   0d5225a4ab6b4c75a70b0ae622aeea91f877babe8a1c2f93da89c887ec27d71f
 Image 2 (atf-2)
  Description:  ARM Trusted Firmware
  Created:      Sun Apr 14 22:36:44 2024
  Type:         Firmware
  Compression:  uncompressed
  Data Size:    40960 Bytes = 40.00 KiB = 0.04 MiB
  Architecture: AArch64
  Load Address: 0xfdcc1000
  Hash algo:    sha256
  Hash value:   3e94d16e6ae2494413482e936aadb88d166d80b9c9976bdc4abf19b438711ce1
 Image 3 (atf-3)
  Description:  ARM Trusted Firmware
  Created:      Sun Apr 14 22:36:44 2024
  Type:         Firmware
  Compression:  uncompressed
  Data Size:    20291 Bytes = 19.82 KiB = 0.02 MiB
  Architecture: AArch64
  Load Address: 0x0006b000
  Hash algo:    sha256
  Hash value:   fde0ef262ba317b0883affa12e3dcf182af8d09224a2fd430085f06ab7633808
 Image 4 (atf-4)
  Description:  ARM Trusted Firmware
  Created:      Sun Apr 14 22:36:44 2024
  Type:         Firmware
  Compression:  uncompressed
  Data Size:    8192 Bytes = 8.00 KiB = 0.01 MiB
  Architecture: AArch64
  Load Address: 0xfdcce000
  Hash algo:    sha256
  Hash value:   c9eb312bf29fb4e40a31caf6b9ab3b1e6bb2038b41a2746a44de2e631125887e
 Image 5 (atf-5)
  Description:  ARM Trusted Firmware
  Created:      Sun Apr 14 22:36:44 2024
  Type:         Firmware
  Compression:  uncompressed
  Data Size:    8192 Bytes = 8.00 KiB = 0.01 MiB
  Architecture: AArch64
  Load Address: 0xfdcd0000
  Hash algo:    sha256
  Hash value:   befba422b8d2e992908b4594bfbd4e063cfee595a03ff4ff35dc1101ed78c3ce
 Image 6 (atf-6)
  Description:  ARM Trusted Firmware
  Created:      Sun Apr 14 22:36:44 2024
  Type:         Firmware
  Compression:  uncompressed
  Data Size:    7888 Bytes = 7.70 KiB = 0.01 MiB
  Architecture: AArch64
  Load Address: 0x00069000
  Hash algo:    sha256
  Hash value:   6ede7a3b44ebd03ad102122522e6a25305e56bffdf4bb4a7a0da7bf521aacdc8
 Image 7 (optee)
  Description:  OP-TEE
  Created:      Sun Apr 14 22:36:44 2024
  Type:         Firmware
  Compression:  uncompressed
  Data Size:    457112 Bytes = 446.40 KiB = 0.44 MiB
  Architecture: AArch64
  Load Address: 0x08400000
  Hash algo:    sha256
  Hash value:   af414b9c9f1a05b058de55de4ad0fa6ec1f40e6b42769454196ee63279570cc7
 Image 8 (fdt)
  Description:  U-Boot dtb
  Created:      Sun Apr 14 22:36:44 2024
  Type:         Flat Device Tree
  Compression:  uncompressed
  Data Size:    14285 Bytes = 13.95 KiB = 0.01 MiB
  Architecture: AArch64
  Hash algo:    sha256
  Hash value:   036cca588089b26828b70f8c47c7e46068cbfec04a1f6b03c8d8b21dbf6c33ac
 Default Configuration: 'conf'
 Configuration 0 (conf)
  Description:  rk3568-evb
  Kernel:       unavailable
  Firmware:     atf-1
  FDT:          fdt
  Loadables:    uboot
                atf-2
                atf-3
                atf-4
                atf-5
                atf-6
                optee
********boot_merger ver 1.31********
Info:Pack loader ok.
pack loader okay! Input: /home/rez-ti/tspi/tspi-linux-sdk/rkbin/RKBOOT/RK3566MINIALL.ini
/home/rez-ti/tspi/tspi-linux-sdk/u-boot

Image(no-signed, version=0): uboot.img (FIT with uboot, trust...) is ready
Image(no-signed): rk356x_spl_loader_v1.16.112.bin (with spl, ddr...) is ready
pack uboot.img okay! Input: /home/rez-ti/tspi/tspi-linux-sdk/rkbin/RKTRUST/RK3568TRUST.ini

Platform RK3568 is build OK, with new .config(make  rk3568_defconfig rk3566.config -j16)
/home/rez-ti/tspi/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-
Sun Apr 14 22:36:44 CST 2024
+ cd ..
Running mk-loader.sh - build_uboot succeeded.
Security not enabled
==========================================
          Start building kernel
==========================================
+ make -C kernel/ -j9 CROSS_COMPILE=/home/rez-ti/tspi/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu- ARCH=arm64 rockchip_linux_defconfig
make: Entering directory '/home/rez-ti/tspi/tspi-linux-sdk/kernel'
#
# No change to .config
#
make: Leaving directory '/home/rez-ti/tspi/tspi-linux-sdk/kernel'
+ make -C kernel/ -j9 CROSS_COMPILE=/home/rez-ti/tspi/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu- ARCH=arm64 tspi-rk3566-user-v10-linux.img
make: Entering directory '/home/rez-ti/tspi/tspi-linux-sdk/kernel'
  CALL    scripts/atomic/check-atomics.sh
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  LZ4C    arch/arm64/boot/Image.lz4
Incorrect parameters
Usage :
      lz4 [arg] [input] [output]

input   : a filename
          with no FILE, or when FILE is - or stdin, read standard input
Arguments :
 -1     : Fast compression (default) 
 -9     : High compression 
 -d     : decompression (default for .lz4 extension)
 -z     : force compression
 -f     : overwrite output without prompting 
 -h/-H  : display help/long help and exit
arch/arm64/boot/Makefile:31: recipe for target 'arch/arm64/boot/Image.lz4' failed
make[2]: *** [arch/arm64/boot/Image.lz4] Error 1
make[2]: *** Deleting file 'arch/arm64/boot/Image.lz4'
arch/arm64/Makefile:170: recipe for target 'Image.lz4' failed
make[1]: *** [Image.lz4] Error 2
make[1]: *** Waiting for unfinished jobs....
arch/arm64/Makefile:214: recipe for target 'tspi-rk3566-user-v10-linux.img' failed
make: *** [tspi-rk3566-user-v10-linux.img] Error 2
make: Leaving directory '/home/rez-ti/tspi/tspi-linux-sdk/kernel'
ERROR: Running /home/rez-ti/tspi/tspi-linux-sdk/device/rockchip/common/scripts/mk-kernel.sh - run_command failed!
ERROR: exit code 2 from line 36:
    $@
ERROR: call stack:
    build-helper: run_command(36)
    mk-kernel.sh: do_build(57)
    mk-kernel.sh: build_hook(130)
    mk-kernel.sh: main(202)
ERROR: Running /home/rez-ti/tspi/tspi-linux-sdk/device/rockchip/common/build-hooks/99-all.sh - build_all failed!
ERROR: exit code 2 from line 26:
    "$SCRIPTS_DIR/mk-kernel.sh"
ERROR: call stack:
    99-all.sh: build_all(26)
    99-all.sh: build_allsave(107)
    99-all.sh: build_hook(132)
    build-helper: try_func(63)
    build-helper: try_hook(95)
    build-helper: source(158)
    99-all.sh: main(142)
ERROR: Running /home/rez-ti/tspi/tspi-linux-sdk/device/rockchip/common/build-hooks/99-all.sh - try_func build_hook allsave failed!
ERROR: exit code 2 from line 67:
    build_hook
ERROR: call stack:
    build-helper: try_func(67)
    build-helper: try_hook(95)
    build-helper: source(158)
    99-all.sh: main(142)
ERROR: Running ./build.sh - run_hooks build allsave failed!
ERROR: exit code 2 from line 152:
    /home/rez-ti/tspi/tspi-linux-sdk/device/rockchip/common/build-hooks/99-all.sh build allsave
ERROR: call stack:
    build.sh: run_hooks(152)
    build.sh: run_build_hooks(171)
    build.sh: main(437)
    build.sh: main(452)
ERROR: Running ./build.sh - run_build_hooks build allsave failed!
ERROR: exit code 2 from line 174:
    build
ERROR: call stack:
    build.sh: run_build_hooks(174)
    build.sh: main(437)
    build.sh: main(452)

**Comment by CmST0us** [comment]
建议使用ubuntu 22.04 版本

**Comment by kelvinchen1119** [comment]
刚刚安装了ubuntu 22.04的版本，然后重新编译还是报错，请帮忙再看下错误日志（其中关于no python2的日志，我已经按照官方吴工的设置做了python2.7和python3的设置；也还是报错...）

rez-ti@Ubuntu22:~/tspi/tspi-linux-sdk$ ./build.sh
Log saved at /home/rez-ti/tspi/tspi-linux-sdk/output/log/2024-04-15_01-01-50

Prebuilt toolchain (for kernel & loader):
/home/rez-ti/tspi/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-

==========================================
          Final configs
==========================================
RK_BOOT_FIT_ITS=boot.its
RK_BOOT_IMG=boot.img
RK_BUILDROOT_CFG=rockchip_rk3566
RK_CHIP=rk3566
RK_CHIP_FAMILY=rk3566
RK_DEBIAN_ARCH=arm64
RK_DEBIAN_ARM64=y
RK_DEBIAN_VERSION=bullseye
RK_DEFCONFIG=/home/rez-ti/tspi/tspi-linux-sdk/device/rockchip/.chips/rk3566_rk3568/tspi-rk3566-ubuntu_defconfig
RK_EXTRA_PARTITION_NUM=2
RK_EXTRA_PARTITION_STR=oem:oem:/oem:ext4:defaults:normal:auto:@userdata:userdata:/userdata:ext4:defaults:normal:auto:@@@
RK_KERNEL_ARCH=arm64
RK_KERNEL_ARM64=y
RK_KERNEL_CFG=rockchip_linux_defconfig
RK_KERNEL_CFG_FRAGMENTS=rockchip_linux_docker.config
RK_KERNEL_DISTROBOOT_CMD=earlycon=uart8250,mmio32,0xfe660000 console=ttyFIQ0 root=PARTUUID=614e0000-0000 rw rootwait
RK_KERNEL_DTB=kernel/arch/arm64/boot/dts/rockchip/tspi-rk3566-user-v10-linux.dtb
RK_KERNEL_DTS=kernel/arch/arm64/boot/dts/rockchip/tspi-rk3566-user-v10-linux.dts
RK_KERNEL_IMG=kernel/arch/arm64/boot/Image
RK_KERNEL_VERSION=5.10
RK_KERNEL_VERSION_REAL=5.10
RK_MISC_IMG=blank-misc.img
RK_PARAMETER=parameter-buildroot-fit.txt
RK_PCBA_CFG=rockchip_rk3566_pcba
RK_RECOVERY_CFG=rockchip_rk3566_recovery
RK_RECOVERY_FIT_ITS=boot4recovery.its
RK_ROOTFS_SYSTEM=ubuntu
RK_ROOTFS_SYSTEM_UBUNTU=y
RK_ROOTFS_TYPE=ext4
RK_ROOTFS_UDEV_RULES=y
RK_SAVE_TRACKED=y
RK_SESSION=2024-04-15_01-01-50
RK_TOOLCHAIN=/home/rez-ti/tspi/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-
RK_UBOOT_CFG=rk3566
RK_USB_ADBD=y
RK_USB_ADBD_BASH=y
RK_USB_ADBD_TCP_PORT=5555
RK_USE_FIT_IMG=y
RK_WIFIBT_CHIP=ALL_AP
RK_WIFIBT_TTY=ttyS1
RK_YOCTO_CFG=rockchip-rk3568-evb
RK_YOCTO_DISPLAY_PLATFORM=wayland
RK_YOCTO_DISPLAY_PLATFORM_WAYLAND=y

==========================================
          Start building allsave
==========================================
==========================================
          Start building all images
==========================================
==========================================
          Start building uboot
==========================================
+ cd u-boot
+ ./make.sh CROSS_COMPILE=/home/rez-ti/tspi/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu- rk3566
## make  rk3568_defconfig rk3566.config -j16
#
# configuration written to .config
#
Using .config as base
Merging ./arch/../configs/rk3566.config
Value of CONFIG_BASE_DEFCONFIG is redefined by fragment ./arch/../configs/rk3566.config:
Previous value: CONFIG_BASE_DEFCONFIG=""
New value: CONFIG_BASE_DEFCONFIG="rk3568_defconfig"

Value of CONFIG_LOADER_INI is redefined by fragment ./arch/../configs/rk3566.config:
Previous value: CONFIG_LOADER_INI=""
New value: CONFIG_LOADER_INI="RK3566MINIALL.ini"

#
# merged configuration written to .config (needs make)
#
scripts/kconfig/conf  --oldconfig Kconfig
#
# configuration written to .config
#
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config.h
  CFG     u-boot.cfg
  GEN     include/autoconf.mk.dep
  CFG     spl/u-boot.cfg
  CFG     tpl/u-boot.cfg
  GEN     include/autoconf.mk
  GEN     tpl/include/autoconf.mk
  GEN     spl/include/autoconf.mk
  CHK     include/config/uboot.release
  CHK     include/generated/timestamp_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  CHK     include/generated/version_autogenerated.h
  CHK     include/generated/generic-asm-offsets.h
  CHK     include/generated/asm-offsets.h
  HOSTCC  tools/mkenvimage.o
  HOSTCC  tools/fit_image.o
  HOSTCC  tools/image-host.o
  HOSTCC  tools/dumpimage.o
  HOSTCC  tools/mkimage.o
  HOSTCC  tools/rockchip/boot_merger.o
  HOSTCC  tools/rockchip/loaderimage.o
  CHK     include/config.h
  HOSTLD  tools/mkenvimage
  CFG     u-boot.cfg
  HOSTLD  tools/loaderimage
  HOSTLD  tools/dumpimage
  HOSTLD  tools/mkimage
tools/rockchip/boot_merger.c: In function 'mergeBoot':
tools/rockchip/boot_merger.c:700:43: warning: '%s' directive output may be truncated writing up to 813 bytes into a region of size 5 [-Wformat-truncation=]
  700 |         snprintf(buffer, sizeof(buffer), "%s", chip);
      |                                           ^~
......
  742 |                 chipType = convertChipType(chip + 2);
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:894,
                 from ././include/compiler.h:25,
                 from <command-line>:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:71:10: note: '__builtin_snprintf' output between 1 and 814 bytes into a destination of size 5
   71 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |                                    __glibc_objsize (__s), __fmt,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |                                    __va_arg_pack ());
      |                                    ~~~~~~~~~~~~~~~~~
tools/rockchip/boot_merger.c: In function 'main':
tools/rockchip/boot_merger.c:895:18: warning: array subscript 20 is outside array bounds of 'char[20]' [-Warray-bounds]
  895 |         str[len] = 0;
      |         ~~~~~~~~~^~~
tools/rockchip/boot_merger.c:933:14: note: while referencing 'name'
  933 |         char name[MAX_NAME_LEN];
      |              ^~~~
  HOSTLD  tools/boot_merger
  CC      arch/arm/cpu/armv8/fwcall.o
  LD      arch/arm/cpu/armv8/built-in.o
  CC      cmd/version.o
  CC      common/main.o
  LD      cmd/built-in.o
  LD      common/built-in.o
  CC      drivers/usb/gadget/f_fastboot.o
  CC      lib/display_options.o
  LD      lib/built-in.o
  LD      drivers/usb/gadget/built-in.o
  LD      u-boot
  OBJCOPY u-boot.srec
  OBJCOPY u-boot-nodtb.bin
start=$(/home/rez-ti/tspi/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-nm u-boot | grep __rel_dyn_start | cut -f 1 -d ' '); end=$(/home/rez-ti/tspi/tspi-linux-sdk/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-nm u-boot | grep __rel_dyn_end | cut -f 1 -d ' '); tools/relocate-rela u-boot-nodtb.bin 0x00a00000 $start $end
  SYM     u-boot.sym
make[2]: 'arch/arm/dts/rk3568-evb.dtb' is up to date.
  COPY    u-boot.dtb
  CAT     u-boot-dtb.bin
  MKIMAGE u-boot.img
  MKIMAGE u-boot-dtb.img
  COPY    u-boot.bin
  ALIGN   u-boot.bin
  COPY    spl/u-boot-spl.dtb
  CC      spl/common/spl/spl.o
  CC      spl/arch/arm/cpu/armv8/fwcall.o
  CC      tpl/arch/arm/mach-rockchip/tpl.o
  CC      tpl/arch/arm/cpu/armv8/fwcall.o
  LD      spl/arch/arm/cpu/armv8/built-in.o
  LD      tpl/arch/arm/mach-rockchip/built-in.o
  LD      tpl/arch/arm/cpu/armv8/built-in.o
  CC      spl/lib/display_options.o
  LD      spl/common/spl/built-in.o
  LD      spl/lib/built-in.o
  LD      tpl/u-boot-tpl
  OBJCOPY tpl/u-boot-tpl-nodtb.bin
  COPY    tpl/u-boot-tpl.bin
  LD      spl/u-boot-spl
  OBJCOPY spl/u-boot-spl-nodtb.bin
  CAT     spl/u-boot-spl-dtb.bin
  COPY    spl/u-boot-spl.bin
  CFGCHK  u-boot.cfg
ERROR: No python2
ERROR: Running /home/rez-ti/tspi/tspi-linux-sdk/device/rockchip/common/scripts/mk-loader.sh - run_command failed!
ERROR: exit code 1 from line 36:
    $@
ERROR: call stack:
    build-helper: run_command(36)
    mk-loader.sh: do_build_uboot(56)
    mk-loader.sh: build_uboot(67)
    mk-loader.sh: build_hook(150)
    mk-loader.sh: main(163)
ERROR: Running /home/rez-ti/tspi/tspi-linux-sdk/device/rockchip/common/build-hooks/99-all.sh - build_all failed!
ERROR: exit code 1 from line 20:
    "$SCRIPTS_DIR/mk-loader.sh" loader
ERROR: call stack:
    99-all.sh: build_all(20)
    99-all.sh: build_allsave(107)
    99-all.sh: build_hook(132)
    build-helper: try_func(63)
    build-helper: try_hook(95)
    build-helper: source(158)
    99-all.sh: main(142)
ERROR: Running /home/rez-ti/tspi/tspi-linux-sdk/device/rockchip/common/build-hooks/99-all.sh - try_func build_hook allsave failed!
ERROR: exit code 1 from line 67:
    build_hook
ERROR: call stack:
    build-helper: try_func(67)
    build-helper: try_hook(95)
    build-helper: source(158)
    99-all.sh: main(142)
ERROR: Running ./build.sh - run_hooks build allsave failed!
ERROR: exit code 1 from line 152:
    /home/rez-ti/tspi/tspi-linux-sdk/device/rockchip/common/build-hooks/99-all.sh build allsave
ERROR: call stack:
    build.sh: run_hooks(152)
    build.sh: run_build_hooks(171)
    build.sh: main(437)
    build.sh: main(452)
ERROR: Running ./build.sh - run_build_hooks build allsave failed!
ERROR: exit code 1 from line 174:
    build
ERROR: call stack:
    build.sh: run_build_hooks(174)
    build.sh: main(437)
    build.sh: main(452)
rez-ti@Ubuntu22:~/tspi/tspi-linux-sdk$

**Comment by CmST0us** [comment]
ERROR: No python2

没有装python2 用apt 安装一下
