### ISSUE TITLE
wifi无法使用

### ISSUE THREAD

**Issue by mzhixian** [CmST0us/tspi-linux-sdk-archived#8]
dmesg如下
[dmesg.txt](https://github.com/CmST0us/tspi-linux-sdk/files/14974444/dmesg.txt)

**Comment by CmST0us** [comment]
![image](https://github.com/CmST0us/tspi-linux-sdk/assets/16432714/e014b050-0177-4197-a881-90b999c32eb8)
左边是成功的log, 右边是失败的log
检查以下是不是 git lfs pull 没有拉全sdk，你的firmware的wifi驱动固件大小不对。
