### ISSUE TITLE
立创·泰山派RK3566官方的repo地址是多少

### ISSUE THREAD

**Issue by hyyoxhk** [CmST0us/tspi-linux-sdk-archived#9]
你好，我买了立创·泰山派RK3566，但是[官方文档](https://lceda001.feishu.cn/wiki/RcTzwNhgeiX57ckmYKPcHpunnWb)上的sdk是百度网盘的，很大（大约15G），每次下载都会中断。我看官方是有repo版本的，你能不能提供一下官方的repo url，我想直接用官方的url下载，非常感谢

**Comment by CmST0us** [comment]
这个我没有，我这里是非官方的SDK
